#!/usr/bin/env bash
# Script to change localhost and facebook.com IPs

# Backup the original hosts file just in case
cp /etc/hosts /etc/hosts.bak

# Remove any existing lines for localhost and facebook.com
sed -i '/localhost/d' /etc/hosts
sed -i '/facebook.com/d' /etc/hosts

# Add new IP mappings
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
